# Generated by Django 3.2.18 on 2023-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_remove_check_defect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_time',
            field=models.DateField(blank=True, null=True, verbose_name='检测时间'),
        ),
    ]
